# Generated by Django 3.2.23 on 2023-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20231212_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.CharField(default='a', max_length=1, verbose_name='Course name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='timePreferences',
            field=models.CharField(default='-', max_length=65, verbose_name="I'd like to finish by"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=65, unique=True, verbose_name='Enter your name'),
        ),
    ]
